name: coverage

on: push

jobs:
  build:
    name: Test and upload to Codecov
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Upload results to Codecov
      run: bash <(curl -s https://codecov.io/bash) -t ${{secrets.CODECOV_TOKEN}}